/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package av1.Fornecedor;

import av1.GravacaoArquivo.ArquivoClienteFornecedor;
import av1.JanelaPrincipal;
import av1.OperacaoCadastro;
import javax.swing.JOptionPane;

/**
 *
 * @author delmi
 */
public class JanelaFornecedor extends javax.swing.JDialog {
    private ModeloTabelaFornecedor modeloPessoa;

    /**
     * Creates new form JanelaFornecedor1
     */
    public JanelaFornecedor() {
        initComponents();
        modeloPessoa = new ModeloTabelaFornecedor(ArquivoClienteFornecedor.carregarFornecedoresArquivo());
        tabelaPessoa.setModel(modeloPessoa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPessoa = new javax.swing.JTable();
        buAlterar = new javax.swing.JButton();
        buExcluir = new javax.swing.JButton();
        buFechar = new javax.swing.JButton();
        buIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Dados de Fornecedor");

        tabelaPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaPessoa);

        buAlterar.setBackground(new java.awt.Color(204, 204, 255));
        buAlterar.setText("Alterar");
        buAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAlterarActionPerformed(evt);
            }
        });

        buExcluir.setBackground(new java.awt.Color(255, 102, 102));
        buExcluir.setText("Excluir");
        buExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buExcluirActionPerformed(evt);
            }
        });

        buFechar.setBackground(new java.awt.Color(255, 153, 153));
        buFechar.setText("Voltar");
        buFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buFecharActionPerformed(evt);
            }
        });

        buIncluir.setBackground(new java.awt.Color(204, 204, 255));
        buIncluir.setText("Incluir");
        buIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(buExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buExcluir)
                        .addGap(145, 145, 145)
                        .addComponent(buFechar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void buAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAlterarActionPerformed
        int indiceFornecedor = tabelaPessoa.getSelectedRow();
        if (indiceFornecedor >= 0){
            Fornecedor fornecedor = modeloPessoa.obterFornecedor(indiceFornecedor); 
            if (JanelaCadastroFornecedor.executar(null, OperacaoCadastro.ocAlterar, fornecedor)) {
                modeloPessoa.atualizarPessoa(indiceFornecedor, fornecedor);
                ArquivoClienteFornecedor.salvarFornecedoresArquivo(modeloPessoa.getListaFornecedores());
            }
        } else {
            JOptionPane.showMessageDialog(null, "É necessário selecionar a passoa.");
        }
    }//GEN-LAST:event_buAlterarActionPerformed

    private void buExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buExcluirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, 
        "Tem certeza que deseja excluir o cliente?", 
        "Confirmar Exclusão", 
        JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            int indiceFornecedor = tabelaPessoa.getSelectedRow();
        if (indiceFornecedor >= 0){
            modeloPessoa.excluirPessoa(indiceFornecedor);
            ArquivoClienteFornecedor.salvarFornecedoresArquivo(modeloPessoa.getListaFornecedores());
        } else {
            JOptionPane.showMessageDialog(null, "É necessário selecionar o fornecedor.");
        }
            System.out.println("Cliente excluído.");
        } else {
            System.out.println("Exclusão cancelada.");
        }

        
        
    }//GEN-LAST:event_buExcluirActionPerformed

    private void buFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buFecharActionPerformed
        new JanelaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buFecharActionPerformed

    private void buIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buIncluirActionPerformed
        Fornecedor fornecedor = new Fornecedor();
        if (JanelaCadastroFornecedor.executar(null, OperacaoCadastro.ocIncluir, fornecedor)) {
            modeloPessoa.incluirPessoa(fornecedor);
            ArquivoClienteFornecedor.salvarFornecedoresArquivo(modeloPessoa.getListaFornecedores());
        }
    }//GEN-LAST:event_buIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaFornecedor dialog = new JanelaFornecedor();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buAlterar;
    private javax.swing.JButton buExcluir;
    private javax.swing.JButton buFechar;
    private javax.swing.JButton buIncluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPessoa;
    // End of variables declaration//GEN-END:variables
}
